language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 61805d05a3229cd7c1a3f564ddb4fcd062549719
  local_dir: dist
  on:
    branch: master

